version: 0.0

os: linux

files:
  - source: /
    destination: /home/ubuntu/dev
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/dev/run_new_was.sh
      timeout: 180
      runas: ubuntu
    - location: scripts/dev/health_check.sh
      timeout: 180
      runas: ubuntu
    - location: scripts/dev/switch.sh
      timeout: 180
      runas: ubuntu