name: deploy
on: 
  push: 
    branches: ["main", "dev"]
permissions: 
  contents: read
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
      with:
        token: ${{  secrets.ACTION_TOKEN  }}
        submodules: true

      # Caching Gradle
    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with: 
        java-version: '17'
        distribution: 'temurin'

    - name: Gradle Authorization
      run: chmod +x gradlew
    - name: Gradle Build Run
      run: ./gradlew build
      
    - name: Create Zip files
      run: zip -r ./$GITHUB_SHA.zip .

    - name: Connecting to AWS
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{  secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{  secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION  }}

    - name: Upload File to S3
      run: | 
        aws s3 cp \
        --region ap-northeast-2 \
        ./$GITHUB_SHA.zip s3://dnd-9th-1-s3

    - name: Request to CodeDeploy
      run: | 
        aws deploy create-deployment \
        --application-name dnd-9th-1-codedeploy \
        --deployment-config-name CodeDeployDefault.AllAtOnce \
        --deployment-group-name dnd-9th-1-deployment-group \
        --s3-location bucket=dnd-9th-1-s3,bundleType=zip,key=$GITHUB_SHA.zip